name: Deploy Song Manager
run-name: ${{ github.actor }} deployed the song-manager
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Song Manager
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: pfadifotos.ch
          username: pfadifot
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: ~/deploy_rondo.sh
